RECIPIENT_STATUS = {
    '4.2.2': {'title': 'Caixa de entrada cheia', 'description': 'A caixa de entrada do destinatário está sem espaço de armazenamento.'},
    '4.3.2': {'title': 'Falha no recebedor', 'description': 'Falha de recebimento por parte do destinatário ou algum bloqueio no destino.'},
    '4.4.0': {'title': 'Falha no recebedor', 'description': 'O servidor de destino não está respondendo da maneira esperada.'},
    '4.4.1': {'title': 'Falha no recebedor', 'description': 'O servidor de destino não está respondendo da maneira esperada.'},
    '4.4.2': {'title': 'Falha no recebedor', 'description': 'Falha de recebimento por parte do destinatário ou algum bloqueio no destino.'},
    '4.4.3': {'title': 'Falha no recebedor', 'description': 'Falha de recebimento por parte do destinatário ou algum bloqueio no destino.'},
    '4.4.7': {'title': 'Falha no recebedor', 'description': 'Falha de comunicação com o servidor do destinatário.'},
    '4.7.1': {'title': 'Falha no recebedor', 'description': 'Falha de recebimento por parte do destinatário ou algum bloqueio no destino.'},
    '5.0.0': {'title': 'Status indefinido', 'description': 'Status indefinido.'},
    '5.1.0': {'title': 'E-mail inexistente', 'description': 'A caixa postal do destinatário não existe no domínio destino, provavelmente foi digitado incorretamente.'},
    '5.1.1': {'title': 'E-mail inexistente', 'description': 'A caixa postal do destinatário não existe no domínio destino, provavelmente foi digitado incorretamente.'},
    '5.1.2': {'title': 'E-mail inexistente', 'description': 'O domínio do destinatário foi digitado de modo incorreto ou o domínio não existe.'},
    '5.1.3': {'title': 'E-mail inexistente', 'description': 'O endereço de e-mail do destinatário possui algum caractere incorreto.'},
    '5.2.2': {'title': 'Caixa de entrada cheia', 'description': 'A caixa de entrada do destinatário está sem espaço de armazenamento.'},
    '5.3.2': {'title': 'Falha no recebedor', 'description': 'Falha de recebimento por parte do destinatário ou algum bloqueio no destino.'},
    '5.3.0': {'title': 'Falha no recebedor', 'description': 'Falha de recebimento por parte do destinatário ou algum bloqueio no destino.'},
    '5.4.4': {'title': 'Falha no recebedor', 'description': 'O servidor do destino falhou ao tentar resolver o nome do domínio remetente.'},
    '5.5.0': {'title': 'Rejeitado pelo recebedor', 'description': 'O servidor de e-mail do destinatário pode estar rejeitando a mensagem por motivos como política de spam ou problemas de autenticação entre os servidores.'},
    '5.5.3': {'title': 'SPAM', 'description': 'Esta mensagem significa que o endereço IP do seu servidor de e­mail está atualmente listado como sendo uma fonte de spam.'},
    '5.7.17': {'title': 'E-mail inexistente', 'description': 'A caixa postal do destinatário não existe no domínio destino, provavelmente foi digitado incorretamente.'},
}
