# Generated by Django 4.0 on 2022-08-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('in_use', models.BooleanField(default=False)),
                ('is_qualified', models.BooleanField(default=False)),
                ('validation_method', models.CharField(choices=[('dns', 'DNS'), ('email', 'E-mail')], default='dns', max_length=20)),
                ('arn', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoadBalancerListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arn', models.CharField(max_length=255)),
                ('load_balancer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws_saas.loadbalancer')),
            ],
        ),
        migrations.CreateModel(
            name='ListenerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws_saas.certificate')),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aws_saas.loadbalancerlistener')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('cname_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cname_value', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aws_saas.certificate')),
            ],
        ),
    ]
