# Generated by Django 4.0 on 2022-08-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedomain',
            name='emails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
