# Generated by Django 4.0 on 2022-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0002_certificatedomain_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadbalancerlistener',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='aws_saas.Certificate', verbose_name='Certificados'),
        ),
        migrations.DeleteModel(
            name='ListenerCertificate',
        ),
    ]
