# Generated by Django 4.0 on 2022-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0003_loadbalancerlistener_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
