# Generated by Django 4.0 on 2022-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0004_alter_certificate_arn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesEmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email_address', 'E-mail'), ('domain', 'Domínio')], default='email_address', max_length=20)),
                ('identity', models.CharField(max_length=255)),
                ('sending_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
