# Generated by Django 4.0.7 on 2024-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0005_sesemailidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesEmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('Bounce', 'Bounce'), ('Complaint', 'Complaint'), ('Delivery', 'Delivery'), ('Send', 'Send'), ('Reject', 'Reject'), ('Open', 'Open'), ('Click', 'Click'), ('RenderingFailure', 'Rendering Failure'), ('DeliveryDelay', 'DeliveryDelay'), ('Subscription', 'Subscription')], max_length=20)),
                ('bounce_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Transient', 'Transient'), ('Undetermined', 'Undetermined')], max_length=20, null=True)),
                ('bounce_sub_type', models.CharField(choices=[('Undetermined', 'Undetermined'), ('General', 'General'), ('NoEmail', 'NoEmail'), ('Suppressed', 'Suppressed'), ('OnAccountSuppressionList', 'OnAccountSuppressionList'), ('MailboxFull', 'MailboxFull'), ('MessageTooLarge', 'MessageTooLarge'), ('ContentRejected', 'ContentRejected'), ('AttachmentRejected', 'AttachmentRejected')], max_length=30, null=True)),
                ('complaint_feedback_type', models.CharField(max_length=30, null=True)),
                ('reject_reason', models.CharField(max_length=155, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('finished', 'finished')], max_length=20)),
            ],
        ),
    ]
