# Generated by Django 4.0.7 on 2024-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0006_sesemailevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesemailevent',
            name='recipient_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sesemailevent',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('finished', 'finished')], default='new', max_length=20),
        ),
    ]
