# Generated by Django 4.0.7 on 2024-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0007_sesemailevent_recipient_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sesemailevent',
            index=models.Index(fields=['status', 'event_type', 'bounce_type'], name='aws_saas_se_status_1b84a5_idx'),
        ),
    ]
