# Generated by Django 5.2.3 on 2025-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_saas', '0008_sesemailevent_aws_saas_se_status_1b84a5_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sesemailevent',
            new_name='aws_saas_se_status_94e706_idx',
            old_name='aws_saas_se_status_1b84a5_idx',
        ),
    ]
